import re

from basecase.basecase import BaseCase


class TestReadBegin(BaseCase):
    def test_read_begin(self):
        res = self.read_begin.read_begin()
        print('请求url：' + res.url)
        print('requestId：' + res.headers['requestId'])
        print(res.json())
        assert res.status_code == 200
        assert res.json()['retCode'] == 0
        assert re.search(r'\w+', res.json()['data']['crtt'])
        assert re.search(r'\d', str(res.json()['data']['isCloseApp']))
        assert re.search(r'\w+', res.json()['data']['systemInText'])
        assert re.search(r'\d+', str(res.json()['data']['vtAmount']))
        assert re.search(r'\d', str(res.json()['data']['atap']))
        assert re.search(r'\w+', res.json()['data']['sjInfo'])
        assert re.search(r'\w+', res.json()['data']['readInText'])
        assert re.search(r'\w+', res.json()['data']['systemOutText'])
        assert re.search(r'\d', str(res.json()['data']['fcat']))
        assert re.search(r'\d', str(res.json()['data']['att']))
        assert re.search(r'\d', str(res.json()['data']['isNotify']))
        assert re.search(r'\w+.\w+.\w+', str(res.json()['data']['backupDomains']))
        assert re.search(r'\d', str(res.json()['data']['isWarmBoot']))
        assert re.search(r'\d', str(res.json()['data']['searchSwitch']))
        assert re.search(r'\d+', str(res.json()['data']['voicePn']))
        assert re.search(r'\d', str(res.json()['data']['adv']))
        assert re.search(r'\d', str(res.json()['data']['isShowVideo']))
        assert re.search(r'\w+', str(res.json()['data']['buttonTip']))
        assert re.search(r'\d', str(res.json()['data']['isrvt']))
        assert re.search(r'\d', str(res.json()['data']['vipAutoPay']))
        assert re.search(r'\d', str(res.json()['data']['isAp']))
        assert re.search(r'lv\d', res.json()['data']['gradeNo'])
        assert re.search(r'\d', str(res.json()['data']['delVbc']))
        assert re.search(r'\d', str(res.json()['data']['hearBook']))
        assert re.search(r'\d', str(res.json()['data']['isInvite']))
        assert re.search(r'\d', str(res.json()['data']['bgRight']['inkPaint']['isLock']))
        assert re.search(r'lv\d', res.json()['data']['bgRight']['inkPaint']['cgradeNo'])
        assert re.search(r'\d', str(res.json()['data']['bgRight']['parchment']['isLock']))
        assert re.search(r'lv\d', res.json()['data']['bgRight']['parchment']['cgradeNo'])
        assert re.search(r'\d', str(res.json()['data']['oppoBrow']))
        assert re.search(r'\d+', str(res.json()['data']['rbav']['registerTime']))
        assert re.search(r'\d+', str(res.json()['data']['rbav']['chapterIndex']))
        assert re.search(r'\d+', str(res.json()['data']['rbav']['registerAfterTime']))
        assert re.search(r'\d', str(res.json()['data']['baiduBrow']))
        assert re.search(r'\d', str(res.json()['data']['isZhichi']))
        assert re.search(r'\w+', res.json()['data']['readOutText'])
        assert re.search(r'\d+', str(res.json()['data']['spaceTime']))
        assert re.search(r'\w+', res.json()['data']['irtt'])
        assert re.search(r'\d', str(res.json()['data']['qah']))
        assert re.search(r'\d+', str(res.json()['data']['currTime']))
        assert re.search(r'\w+', res.json()['data']['artt'])
        assert re.search(r'\w+', res.json()['data']['successTip'])
        assert re.search(r'\d', str(res.json()['data']['qao']))
        assert re.search(r'\d', str(res.json()['data']['isUpa']))
        assert re.search(r'\d', str(res.json()['data']['ysRight']['JPermeng']['isLock']))
        assert re.search(r'lv\d', res.json()['data']['ysRight']['JPermeng']['cgradeNo'])
        assert re.search(r'\d', str(res.json()['data']['ysRight']['JPnuannuan']['isLock']))
        assert re.search(r'lv\d', str(res.json()['data']['ysRight']['JPnuannuan']['cgradeNo']))
        assert re.search(r'\d', str(res.json()['data']['bookEffect']))
        assert re.search(r'\d', str(res.json()['data']['checkAgree']))
        assert re.search(r'\w+', res.json()['data']['rpuv'])
        assert re.search(r'\d', str(res.json()['data']['buttonPosition']))
        assert re.search(r'\d', str(res.json()['data']['isAddDesktop']))
        assert re.search(r'\d', str(res.json()['data']['readQuitNum']))
        assert re.search(r'\d', str(res.json()['data']['readNum']))
        assert re.search(r'\d', str(res.json()['data']['bsbl']))
        assert re.search(r'\w+', res.json()['data']['nrtt'])
        assert re.search(r'\w+', res.json()['data']['brtt'])
        assert re.search(r'\d', str(res.json()['data']['ssydSign']))
        assert re.search(r'\d', str(res.json()['data']['courseQuit']))
